# ==========================================
# Import AWS Secrets Manager
# ==========================================
spring.config.import=aws-secretsmanager:${DOCUMENT_DB_SECRET_NAME}

# ==========================================
# AWS Configuration
# ==========================================
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.use-default-aws-credentials-chain=true

# ==========================================
# Application
# ==========================================
spring.application.name=grpc-customer-svc

# ==========================================
# gRPC
# ==========================================
spring.grpc.server.port=9090
spring.grpc.server.enable-reflection=true

# ==========================================
# MongoDB / Amazon DocumentDB
# ==========================================
# spring.data.mongodb.uri=mongodb://${username}:${password}@${customer_endpoint}:${port}/?tls=true&tlsCAFile=/app/certs/rds-combined-ca-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false





